config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :profiles
  devise_for :users
  resources :locations
  resources :subsidiaries
  resources :cp_categories
  resources :tasks
  resources :cycles
  resources :service_types
  resources :service_states
  resources :order_states
  resources :rols
  resources :companies
  resources :models
  resources :cm_categories
  resources :brands
  resources :municipalities
  resources :makers
  resources :departments

  root :to => 'static_pages#index'
  
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/credit'
  get 'static_pages/index'
  get 'static_pages/news_offers'
  get 'static_pages/our_history'
  get 'static_pages/our_mission'
  get 'static_pages/our_vision'
  get 'static_pages/service_backup'
  get 'static_pages/service_licensing'
  get 'static_pages/service_outsourcing'
  get 'static_pages/service_security'
  get 'static_pages/service_telecommunications'
  get 'static_pages/service_uptime'
  post 'static_pages/our_history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cp_category.rb
class CpCategory < ApplicationRecord

  has_many :cm_categories

  def self.search(search, page)  
      where("codigo_CP LIKE ? OR nombre_CP LIKE ?",
      "%#{search}%", "%#{search}%").paginate(page: page, per_page: 5).order("codigo_CP")     
  end

  def name
	self.nombre_CP
  end

end

app/controllers/cp_categories_controller.rb
class CpCategoriesController < AppController
  before_action :set_cp_category, only: [:show, :edit, :update, :destroy]

  # GET /cp_categories
  # GET /cp_categories.json
  def index
    @cp_categories = CpCategory.search(params[:search], params[:page])
  end

  # GET /cp_categories/1
  # GET /cp_categories/1.json
  def show
  end

  # GET /cp_categories/new
  def new
    @cp_category = CpCategory.new
  end

  # GET /cp_categories/1/edit
  def edit
  end

  # POST /cp_categories
  # POST /cp_categories.json
  def create
    @cp_category = CpCategory.new(cp_category_params)

    respond_to do |format|
      if @cp_category.save
        format.html { redirect_to cp_categories_url, notice: 'Categoria registrada exitosamente.' }
        format.json { render :show, status: :created, location: @cp_category }
      else
        format.html { render :new }
        format.json { render json: @cp_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cp_categories/1
  # PATCH/PUT /cp_categories/1.json
  def update
    respond_to do |format|@cp_categories
      if @cp_category.update(cp_category_params)
        format.html { redirect_to cp_categories_url, notice: 'Categoria actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @cp_category }
      else
        format.html { render :edit }
        format.json { render json: @cp_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cp_categories/1
  # DELETE /cp_categories/1.json
  def destroy
    @cp_category.destroy
    respond_to do |format|
      format.html { redirect_to cp_categories_url, notice: 'Categoria eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cp_category
      @cp_category = CpCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cp_category_params
      params.require(:cp_category).permit(:codigo_CP, :nombre_CP, :estado_CP)
    end
end

app/helpers/cp_categories_helper.rb
module CpCategoriesHelper
end

app/views/cp_categories/_edit.html.erb
<div class="modal fade" id="modaledit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Actualizar Categoría</h1>
      </div>
      <div class="modal-body">
		    <%= render 'form', cp_category: @cp_category %>
      </div>
      <div class="modal-footer">
		    <%= link_to 'Regresar', cp_categories_path, class: "btn btn-default" %>   
      </div>
    </div>
  </div>
</div>

app/views/cp_categories/_form.html.erb
<%= simple_form_for(@cp_category) do |f| %>
  <%= f.error_notification %>  
  <div class="row">
    <div class="col-md-2 col-lg-4">
      <%= f.input :codigo_CP, label:'Código' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-12">
      <%= f.input :nombre_CP, label:'Categoría Productos' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :estado_CP, label:'Estado', as: :radio_buttons, collection: [['ACTIVO', 'true'], ['INACTIVO', 'false']] %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

app/views/cp_categories/_new.html.erb
<div class="modal fade" id="modalnew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Registrar Nueva Categoría</h1>
      </div>
      <div class="modal-body" >
		    <%= render 'form', cp_category: @cp_category %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', cp_categories_path, class: "btn btn-default" %>      
      </div>
      </div>
    </div>
  </div>
</div>

app/views/cp_categories/_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Detalles Categoría </h1>
      </div>
      <div class="modal-body">
        <p>
          <strong>Codigo:</strong>
          <%= @cp_category.codigo_CP %>
        </p>
        <p>
          <strong>Categoría Productos:</strong>
          <%= @cp_category.nombre_CP %>
        </p>
        <p>
          <strong>Estado:</strong>
          <%=  @cp_category.estado_CP  ? 'ACTIVO' : 'INACTIVO'%>
        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', cp_categories_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/cp_categories/edit.js.erb
$('<%= j render "edit", id: "modaledit" %>').modal();

app/views/cp_categories/index.html.erb
<% if notice == nil %>
  <p id="notice"><%= notice %></p>
<% else %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div Class=pandora >
  <div class="modal-content" >
    <div class="container" >     
      <div class="card" > 
        <div class="card-block" >
          <br>
          <%= form_tag cp_categories_path, class: "form-inline", role: "form",  method: 'get' do %>
            &nbsp;&nbsp;&nbsp;
            <div class="form-group">
              <%= search_field_tag :search, params[:search], :class => "form-control",
              placeholder: "Digite el Código o Nombre de la categoría a buscar ...", size: "50" %>
            </div>
            &nbsp;&nbsp;&nbsp;
            <button class="btn btn-info"> Buscar </button>
          <% end %>
          <br>
        </div>
      </div>
      <h1>&nbsp;CATEGORÍAS DE PRODUCTOS</h1>
      <div>&nbsp;
        <td><%= link_to 'Nuevo', new_cp_category_path, remote: true, class: "btn btn-success" %></td>
      </div>
      <div class = "card shadow mb-4" >
        <div class = "card body" >
          <div class="table-responsive">
            <table class="table"remote: true>
              <thead>
                <tr>
                  <th>Codigo</th>
                  <th>Categoría</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @cp_categories.each do |cp_category| %>
                  <tr>
                    <td><%= cp_category.codigo_CP %></td>
                    <td><%= cp_category.nombre_CP %></td>
                    <td><%= link_to 'Detalles', cp_category, remote: true, class: "btn btn-info" %></td>
                    <td><%= link_to 'Actualizar', edit_cp_category_path(cp_category), remote: true, class: "btn btn-warning" %></td>
                    <td><%= link_to 'Eliminar', cp_category, method: :delete, data: { confirm: 'Está seguro?' }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <br>
        </div>
        &nbsp;&nbsp; Categorias: <%= @cp_categories.count %> 
        <br>
        &nbsp;&nbsp; <%= will_paginate @cp_categories, :previous_label=> 'Anterior&nbsp;', :next_label=> '&nbsp;Siguiente' %>
      </div>
    </div>       
  </div>
</div>

app/views/cp_categories/new.js.erb
$('<%= j render "new", id: "modalnew" %>').modal();

app/views/cp_categories/show.js.erb
$('<%= j render "show", title: "Ventana" %>').modal();