config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :profiles
  devise_for :users
  resources :locations
  resources :subsidiaries
  resources :cp_categories
  resources :tasks
  resources :cycles
  resources :service_types
  resources :service_states
  resources :order_states
  resources :rols
  resources :companies
  resources :models
  resources :cm_categories
  resources :brands
  resources :municipalities
  resources :makers
  resources :departments

  root :to => 'static_pages#index'
  
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/credit'
  get 'static_pages/index'
  get 'static_pages/news_offers'
  get 'static_pages/our_history'
  get 'static_pages/our_mission'
  get 'static_pages/our_vision'
  get 'static_pages/service_backup'
  get 'static_pages/service_licensing'
  get 'static_pages/service_outsourcing'
  get 'static_pages/service_security'
  get 'static_pages/service_telecommunications'
  get 'static_pages/service_uptime'
  post 'static_pages/our_history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_state.rb
class OrderState < ApplicationRecord

  def self.search(search, page)  
      where("codigo_Ost LIKE ? OR nombre_Ost LIKE ?",
      "%#{search}%", "%#{search}%").paginate(page: page, per_page: 5).order("codigo_Ost")     
  end

  def name
	self.nombre_Ost
  end

end

app/controllers/order_states_controller.rb
class OrderStatesController < AppController
  before_action :set_order_state, only: [:show, :edit, :update, :destroy]

  # GET /order_states
  # GET /order_states.json
  def index
    @order_states = OrderState.search(params[:search], params[:page])
  end

  # GET /order_states/1
  # GET /order_states/1.json
  def show
  end

  # GET /order_states/new
  def new
    @order_state = OrderState.new
  end

  # GET /order_states/1/edit
  def edit
  end

  # POST /order_states
  # POST /order_states.json
  def create
    @order_state = OrderState.new(order_state_params)

    respond_to do |format|
      if @order_state.save
        format.html { redirect_to order_states_url, notice: 'Estado de Orden registrado exitosamente.' }
        format.json { render :show, status: :created, location: @order_state }
      else
        format.html { render :new }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_states/1
  # PATCH/PUT /order_states/1.json
  def update
    respond_to do |format|
      if @order_state.update(order_state_params)
        format.html { redirect_to order_states_url, notice: 'Estado de Orden actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @order_state }
      else
        format.html { render :edit }
        format.json { render json: @order_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_states/1
  # DELETE /order_states/1.json
  def destroy
    @order_state.destroy
    respond_to do |format|
      format.html { redirect_to order_states_url, notice: 'Estado de Orden eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_state
      @order_state = OrderState.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_state_params
      params.require(:order_state).permit(:codigo_Ost, :nombre_Ost, :descripcion_Ost, :estado_Ost)
    end
end

app/helpers/order_states_helper.rb
module OrderStatesHelper

  def estado(x)
    if x == true
	  return "Activo"
	else
	  return "Inactivo"
	end
  end
  	
end

app/views/order_states/_edit.html.erb
<div class="modal fade" id="modaledit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Actualizar Estado</h1>
      </div>
      <div class="modal-body">
		    <%= render 'form', order_state: @order_state %>
      </div>
      <div class="modal-footer">
		    <%= link_to 'Regresar', order_states_path, class: "btn btn-default" %>   
      </div>
    </div>
  </div>
</div>

app/views/order_states/_form.html.erb
<%= simple_form_for(@order_state) do |f| %>
  <%= f.error_notification %>  
  <div class="row">
    <div class="col-md-2 col-lg-4">
      <%= f.input :codigo_Ost, label:'Código' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-6">
      <%= f.input :nombre_Ost, label:'Estado' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-12">
      <%= f.input :descripcion_Ost, label:'Descripción' %>
    </div>
  </div>  
  <div class="form-group">
    <%= f.input :estado_Ost, label:'Estado', as: :radio_buttons, collection: [['ACTIVO', 'true'], ['INACTIVO', 'false']] %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

app/views/order_states/_new.html.erb
<div class="modal fade" id="modalnew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Registrar Nuevo Estado</h1>
      </div>
      <div class="modal-body" >
		    <%= render 'form', order_state: @order_state %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', order_states_path, class: "btn btn-default" %>      
      </div>
      </div>
    </div>
  </div>
</div>

app/views/order_states/_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Detalles del Estado</h1>
      </div>
      <div class="modal-body">
        <p>
          <strong>Código:</strong>
          <%= @order_state.codigo_Ost %>
        </p>
        <p>
          <strong>Estado:</strong>
          <%= @order_state.nombre_Ost %>
        </p>
        <p>
          <strong>Descripción:</strong>
          <%= @order_state.descripcion_Ost %>
        </p>
        <p>
          <strong>Estado:</strong>
          <%= @order_state.estado_Ost ? 'ACTIVO' : 'INACTIVO'%>
        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', order_states_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/order_states/edit.js.erb
$('<%= j render "edit", id: "modaledit" %>').modal();

app/views/order_states/index.html.erb
<% if notice == nil %>
  <p id="notice"><%= notice %></p>
<% else %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div Class=pandora>
  <div class="modal-content" >
    <div class="container" >
      <div class="card">
        <div class="card-block">  
          <br>
          <%= form_tag order_states_path, class: "form-inline", role: "form",  method: 'get' do %>
            &nbsp;&nbsp;&nbsp;
            <div class="form-group">
              <%= search_field_tag :search, params[:search], :class => "form-control",
                placeholder: "Digite el Código o Nombre del Estado de Orden a buscar ...", size: "50" %>
            </div>
            &nbsp;&nbsp;&nbsp;
            <button class="btn btn-info"> Buscar </button>
          <% end %>
          <br>
        </div>
      </div>
      <h1>&nbsp;ESTADOS DE ORDEN</h1>
      <div>&nbsp;
        <td><%= link_to 'Nuevo', new_order_state_path, remote: true, class: "btn btn-success" %></td>
      </div>
      <div class = "card shadow mb-4">
        <div class = "card body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Estado</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @order_states.each do |order_state| %>
                  <tr>
                    <td><%= order_state.codigo_Ost %></td>
                    <td><%= order_state.nombre_Ost %></td>
                    <td><%= link_to 'Detalles', order_state, remote: true, class: "btn btn-info" %></td>
                    <td><%= link_to 'Actualizar', edit_order_state_path(order_state), remote: true, class: "btn btn-warning" %></td>
                    <td><%= link_to 'Eliminar', order_state, method: :delete, data: { confirm: 'Está seguro?' }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <br>
        </div>
        &nbsp;&nbsp; Estado de Ordenes: <%= @order_states.count %> 
        <br>
        &nbsp;&nbsp; <%= will_paginate @order_states, :previous_label=> 'Anterior&nbsp;', :next_label=> '&nbsp;Siguiente' %>
      </div>
    </div>
  </div>
</div>

app/views/order_states/new.js.erb
$('<%= j render "new", id: "modalnew" %>').modal();

app/views/order_states/show.js.erb
$('<%= j render "show", title: "Ventana" %>').modal();