config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :profiles
  devise_for :users
  resources :locations
  resources :subsidiaries
  resources :cp_categories
  resources :tasks
  resources :cycles
  resources :service_types
  resources :service_states
  resources :order_states
  resources :rols
  resources :companies
  resources :models
  resources :cm_categories
  resources :brands
  resources :municipalities
  resources :makers
  resources :departments

  root :to => 'static_pages#index'
  
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/credit'
  get 'static_pages/index'
  get 'static_pages/news_offers'
  get 'static_pages/our_history'
  get 'static_pages/our_mission'
  get 'static_pages/our_vision'
  get 'static_pages/service_backup'
  get 'static_pages/service_licensing'
  get 'static_pages/service_outsourcing'
  get 'static_pages/service_security'
  get 'static_pages/service_telecommunications'
  get 'static_pages/service_uptime'
  post 'static_pages/our_history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  
  has_many :subsidiaries
  has_many :profiles

  def self.search(search, page)  
      where("codigo_Com LIKE ? OR nombre_Com LIKE ?",
      "%#{search}%", "%#{search}%").paginate(page: page, per_page: 5).order("codigo_Com")     
  end

  def name
    self.nombre_Com
  end

end

app/controllers/companies_controller.rb
class CompaniesController < AppController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.search(params[:search], params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: 'Empresa registrada exitosamente.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_url, notice: 'Empresa actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Empresa eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:codigo_Com, :nombre_Com, :descripcion_Com, :estado_Com)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper

  def estado(x)
	if x == true
      return "Activo"
	else
	  return "Inactivo"
	end
  end

end

app/views/companies/_edit.html.erb
<div class="modal fade" id="modaledit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Actualizar Empresa</h1>
      </div>
      <div class="modal-body">
		    <%= render 'form', company: @company %>
      </div>
      <div class="modal-footer">
		    <%= link_to 'Regresar', companies_path, class: "btn btn-default" %>   
      </div>
    </div>
  </div>
</div>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>  
  <div class="row">
    <div class="col-md-2 col-lg-4">
      <%= f.input :codigo_Com, label:'Nit / Rut' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-6">
      <%= f.input :nombre_Com, label:'Empresa' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-12">
      <%= f.input :descripcion_Com, label:'Descripción' %>
    </div>
  </div>  
  <div class="form-group">
    <%= f.input :estado_Com, label:'Estado', as: :radio_buttons, collection: [['ACTIVO', 'true'], ['INACTIVO', 'false']] %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

app/views/companies/_new.html.erb
<div class="modal fade" id="modalnew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Registrar Nueva Empresa</h1>
      </div>
      <div class="modal-body" >
		    <%= render 'form', company: @company %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', companies_path, class: "btn btn-default" %>      
      </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Detalles de la Empresa</h1>
      </div>
      <div class="modal-body">
        <p>
          <strong>Nit / Rut:</strong>
          <%= @company.codigo_Com %>
        </p>
        <p>
          <strong>Empresa:</strong>
          <%= @company.nombre_Com %>
        </p>
        <p>
          <strong>Descripción:</strong>
          <%= @company.descripcion_Com %>
        </p>
        <p>
          <strong>Estado:</strong>
          <%= @company.estado_Com ? 'ACTIVO' : 'INACTIVO'%>
        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', companies_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/edit.js.erb
$('<%= j render "edit", id: "modaledit" %>').modal();

app/views/companies/index.html.erb
<% if notice == nil %>
  <p id="notice"><%= notice %></p>
<% else %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div Class=pandora>
  <div class="modal-content" >
    <div class="container" >
      <div class="card">
        <div class="card-block">  
          <br>
          <%= form_tag companies_path, class: "form-inline", role: "form",  method: 'get' do %>
            &nbsp;&nbsp;&nbsp;
            <div class="form-group">
              <%= search_field_tag :search, params[:search], :class => "form-control",
                placeholder: "Digite el Código o Nombre de la Empresa a buscar ...", size: "50" %>
            </div>
            &nbsp;&nbsp;&nbsp;
            <button class="btn btn-info"> Buscar </button>
          <% end %>
          <br>
        </div>
      </div>
      <h1>&nbsp;EMPRESAS</h1>
      <div>&nbsp;
        <td><%= link_to 'Nuevo', new_company_path, remote: true, class: "btn btn-success" %></td>
      </div>
      <div class = "card shadow mb-4">
        <div class = "card body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>NIT / RUT / CC</th>
                  <th>EMPRESA</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @companies.each do |company| %>
                  <tr>
                    <td><%= company.codigo_Com %></td>
                    <td><%= company.nombre_Com %></td>
                    <td><%= link_to 'Detalles', company, remote: true, class: "btn btn-info" %></td>
                    <td><%= link_to 'Actualizar', edit_company_path(company), remote: true, class: "btn btn-warning" %></td>
                    <td><%= link_to 'Eliminar', company, method: :delete, data: { confirm: 'Está seguro?' }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <br>
        </div>
        &nbsp;&nbsp; Empresas: <%= @companies.count %> 
        <br>
        &nbsp;&nbsp; <%= will_paginate @companies, :previous_label=> 'Anterior&nbsp;', :next_label=> '&nbsp;Siguiente' %>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.js.erb
$('<%= j render "new", id: "modalnew" %>').modal();

app/views/companies/show.js.erb
$('<%= j render "show", title: "Ventana" %>').modal();