config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :profiles
  devise_for :users
  resources :locations
  resources :subsidiaries
  resources :cp_categories
  resources :tasks
  resources :cycles
  resources :service_types
  resources :service_states
  resources :order_states
  resources :rols
  resources :companies
  resources :models
  resources :cm_categories
  resources :brands
  resources :municipalities
  resources :makers
  resources :departments

  root :to => 'static_pages#index'
  
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/credit'
  get 'static_pages/index'
  get 'static_pages/news_offers'
  get 'static_pages/our_history'
  get 'static_pages/our_mission'
  get 'static_pages/our_vision'
  get 'static_pages/service_backup'
  get 'static_pages/service_licensing'
  get 'static_pages/service_outsourcing'
  get 'static_pages/service_security'
  get 'static_pages/service_telecommunications'
  get 'static_pages/service_uptime'
  post 'static_pages/our_history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service_state.rb
class ServiceState < ApplicationRecord

  def self.search(search, page)  
      where("codigo_Sta LIKE ? OR nombre_Sta LIKE ?",
      "%#{search}%", "%#{search}%").paginate(page: page, per_page: 5).order("codigo_Sta")     
  end

  def name
	self.nombre_Sta
  end

end

app/controllers/service_states_controller.rb
class ServiceStatesController < AppController
  before_action :set_service_state, only: [:show, :edit, :update, :destroy]

  # GET /service_states
  # GET /service_states.json
  def index
    @service_states = ServiceState.search(params[:search], params[:page])
  end

  # GET /service_states/1
  # GET /service_states/1.json
  def show
  end

  # GET /service_states/new
  def new
    @service_state = ServiceState.new
  end

  # GET /service_states/1/edit
  def edit
  end

  # POST /service_states
  # POST /service_states.json
  def create
    @service_state = ServiceState.new(service_state_params)

    respond_to do |format|
      if @service_state.save
        format.html { redirect_to service_states_url, notice: 'Estado de Servicio registrado exitosamente.' }
        format.json { render :show, status: :created, location: @service_state }
      else
        format.html { render :new }
        format.json { render json: @service_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_states/1
  # PATCH/PUT /service_states/1.json
  def update
    respond_to do |format|
      if @service_state.update(service_state_params)
        format.html { redirect_to service_states_url, notice: 'Estado de Servicio actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @service_state }
      else
        format.html { render :edit }
        format.json { render json: @service_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_states/1
  # DELETE /service_states/1.json
  def destroy
    @service_state.destroy
    respond_to do |format|
      format.html { redirect_to service_states_url, notice: 'Estado de Servicio eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_state
      @service_state = ServiceState.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_state_params
      params.require(:service_state).permit(:codigo_Sta, :nombre_Sta, :descripcion_Sta, :estado_Sta)
    end
end

app/helpers/service_states_helper.rb
module ServiceStatesHelper

  def estado(x)
    if x == true
	  return "Activo"
	else
	  return "Inactivo"
	end
  end

end

app/views/service_states/_edit.html.erb
<div class="modal fade" id="modaledit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Actualizar Estado</h1>
      </div>
      <div class="modal-body">
		    <%= render 'form', service_state: @service_state %>
      </div>
      <div class="modal-footer">
		    <%= link_to 'Regresar', service_states_path, class: "btn btn-default" %>   
      </div>
    </div>
  </div>
</div>

app/views/service_states/_form.html.erb
<%= simple_form_for(@service_state) do |f| %>
  <%= f.error_notification %>  
  <div class="row">
    <div class="col-md-2 col-lg-4">
      <%= f.input :codigo_Sta, label:'Código' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-6">
      <%= f.input :nombre_Sta, label:'Estado' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-lg-12">
      <%= f.input :descripcion_Sta, label:'Descripción' %>
    </div>
  </div>  
  <div class="form-group">
    <%= f.input :estado_Sta, label:'Estado', as: :radio_buttons, collection: [['ACTIVO', 'true'], ['INACTIVO', 'false']] %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

app/views/service_states/_new.html.erb
<div class="modal fade" id="modalnew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Registrar Nuevo Estado</h1>
      </div>
      <div class="modal-body" >
		    <%= render 'form', service_state: @service_state %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', service_states_path, class: "btn btn-default" %>      
      </div>
      </div>
    </div>
  </div>
</div>

app/views/service_states/_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">Detalles del Estado</h1>
      </div>
      <div class="modal-body">
        <p>
          <strong>Código:</strong>
          <%= @service_state.codigo_Sta %>
        </p>
        <p>
          <strong>Estado de Servicio:</strong>
          <%= @service_state.nombre_Sta %>
        </p>
        <p>
          <strong>Descripción:</strong>
          <%= @service_state.descripcion_Sta %>
        </p>
        <p>
          <strong>Estado:</strong>
          <%= @service_state.estado_Sta ? 'ACTIVO' : 'INACTIVO'%>
        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Regresar', service_states_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/service_states/edit.js.erb
$('<%= j render "edit", id: "modaledit" %>').modal();

app/views/service_states/index.html.erb
<% if notice == nil %>
  <p id="notice"><%= notice %></p>
<% else %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div Class=pandora>
  <div class="modal-content" >
    <div class="container" >
      <div class="card">
        <div class="card-block">  
          <br>
          <%= form_tag service_states_path, class: "form-inline", role: "form",  method: 'get' do %>
            &nbsp;&nbsp;&nbsp;
            <div class="form-group">
              <%= search_field_tag :search, params[:search], :class => "form-control",
                placeholder: "Ingrese el Código o nombre del Estado de Servicio a buscar ...", size: "50" %>
            </div>
            &nbsp;&nbsp;&nbsp;
            <button class="btn btn-info"> Buscar </button>
          <% end %>
          <br>
        </div>
      </div>
      <h1>&nbsp;ESTADOS DE SERVICIO</h1>
      <div>&nbsp;
        <td><%= link_to 'Nuevo', new_service_state_path, remote: true, class: "btn btn-success" %></td>
      </div>
      <div class = "card shadow mb-4">
        <div class = "card body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Estado de Servicio</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @service_states.each do |service_state| %>
                  <tr>
                    <td><%= service_state.codigo_Sta %></td>
                    <td><%= service_state.nombre_Sta %></td>
                    <td><%= link_to 'Detalles', service_state, remote: true, class: "btn btn-info" %></td>
                    <td><%= link_to 'Actualizar', edit_service_state_path(service_state), remote: true, class: "btn btn-warning" %></td>
                    <td><%= link_to 'Eliminar', service_state, method: :delete, data: { confirm: "¿Está seguro de eliminar: #{service_state.nombre_Sta}?" }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <br>
        </div>
        &nbsp;&nbsp; Estados de Servicios: <%= @service_states.count %> 
        <br>
        &nbsp;&nbsp; <%= will_paginate @service_states, :previous_label=> 'Anterior&nbsp;', :next_label=> '&nbsp;Siguiente' %>
      </div>
    </div>
  </div>
</div>

app/views/service_states/new.js.erb
$('<%= j render "new", id: "modalnew" %>').modal();

app/views/service_states/show.js.erb
$('<%= j render "show", title: "Ventana" %>').modal();